# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ii1xz8M_epqg3PZD0hnrt-dK3Vz5XWgq
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data_url = "https://github.com/HamoyeHQ/HDSC-Introduction-to-Python-for-machine-learning/files/7768140/FoodBalanceSheets_E_Africa_NOFLAG.csv"

data = pd.read_url(data_url)

